version: '3.4'

services:
  microrabitbanking:
    image: ${DOCKER_REGISTRY-}microrabitbanking
    build:
      context: .
      dockerfile: MicroServicesRabitMq.Banking.Api/Dockerfile
    links:
      - sqlserver  
      - rabbitmq
  microrabittransfer:
    image: ${DOCKER_REGISTRY-}microrabittransfer
    build:
      context: .
      dockerfile: MicroServicesRabitMq.Transfer.Api/Dockerfile
    links:
      - sqlserver
      - rabbitmq
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Numan01KIZILIRMAK"
    volumes:
      - ./data/mssql:/var/opt/mssql3
    ports:
      - '1433'
    expose:
      - 1433
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"